version: '3.3'

# repo: https://github/ballab1/python.git

services:
    python:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: python
                FROM_BASE: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest} 
                PYTHON_VERSION: ${PYTHON_VERSION:-3.9.13-r1}
            cache_from:
                - ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}thirdparty/${CONTAINER_OS:-alpine}:${OS_VERSION:-3.18.2}
                - ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest} 
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: python
                container.parent: $CONTAINER_PARENT 
                version.cbf: $CBF_VERSION
        container_name: python
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        image: ${DOCKER_REGISTRY:-s2.ubuntu.home:5000/}${CONTAINER_OS:-alpine}/python/${PYTHON_VERSION:-3.9.13-r1}:${CONTAINER_TAG:-latest}
